export const extraSize = { XL_SCREEN_SUBTITLE_EXTRA_SIZE: 25 };

export const positions = {
  TOP_MOBILE: 110,
  TOP_TABLET: 208,
  TOP_LAPTOP: 204,
  TOP_DESKTOP: 314,
  TOP_XL: 409,
  BR_TOP_MOBILE: 208,
  BR_TOP_TABLET: 208,
  BR_TOP_LAPTOP: 205,
  BR_TOP_DESKTOP: 315,
  BR_TOP_XL: 409,
  SINGLE_BR_TOP_MOBILE: 304,
  SINGLE_BR_TOP_TABLET: 404,
  SINGLE_BR_TOP_LAPTOP: 406,
  SINGLE_BR_TOP_DESKTOP: 434,
  SINGLE_BR_TOP_XL: 659 - extraSize.XL_SCREEN_SUBTITLE_EXTRA_SIZE,
};
